apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskproducer
spec:
  selector:
    matchLabels:
      app: taskproducer
  template:
    metadata:
      labels:
        app: taskproducer
    spec:
      containers:
      - name: taskproducer
        image: lidiyaj/taskproducer
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: taskproducer
spec:
  type: NodePort
  selector:
    app: taskproducer
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31500